services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    environment:
      FIREBASE_PROJECT_ID: gym-note-app
      RAILS_ENV: development
      RUBY_DEBUG_OPEN: true
      USE_FIREBASE_EMULATOR: true
    stdin_open: true
    tty: true

volumes:
  bundle_data:
