services:
  db:
    image: mariadb:11.2
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: gym_note_development
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    command: ['mariadbd', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: gym_note_development
      RAILS_ENV: development
    stdin_open: true
    tty: true

volumes:
  mariadb_data:
  bundle_data:
